name = "compcert"
version = "0.1.0"
defaultTargets = ["Compcert"]

[[lean_lib]]
name = "Compcert"

[[lean_exe]]
name = "tests"
root = "Tests.Basic"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"
